[package]
name = "biscuit"
version = "0.0.1"
authors = ["Yong Wen Chua <me@yongwen.xyz>", "Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "A library to work with JSON Web Tokens (JWT)."
homepage = "https://github.com/lawliet89/rust-jwt"
repository = "https://github.com/lawliet89/rust-jwt"
keywords = ["jwt", "web", "token", "json"]

[lib]
name = "biscuit"
path = "src/lib.rs"
test = true
doctest = true
doc = true

[dependencies]
chrono = "0.3"
ring = { version = "0.7", features = ["rsa_signing"] }
rustc-serialize = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_json = { version = "0.9", features = ["preserve_order"] }
untrusted = "0.3"

[dev-dependencies]
serde_test = "0.9"
